trajectory:
    publisher_topic: trajectory_generation/reference_trajectory
    waypoint_server_topic: trajectory_generation/set_parameters

controller:
    cmd_angular_vel_topic: controller/cmd_angular_vel
    cmd_pwm_topic: controller/cmd_motor_pwm

wmr_state_feedback:
    encoder:
        pose_topic: wmr_state_feedback/position_from_encoder
        ang_vel_topic: wmr_state_feedback/encoder/actual_ang_vel
        left_timeStamped_topic: wmr_state_feedback/encoder_left_timeStamped
        right_timeStamped_topic: wmr_state_feedback/encoder_right_timeStamped
    gps:
        pose_topic: wmr_state_feedback/position_from_gps

    feedback_selected: wmr_state_feedback/wmr_selected_feedback
